name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 1.2.0
homepage: https://github.com/leisim/dartx

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  characters: ^1.1.0
  collection: ^1.15.0
  crypto: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  time: ^2.0.0

dev_dependencies:
  fake_async: ^1.2.0
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
