name: dartx
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.1.2
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/dartx

environment:
  sdk: ">=2.6.0-dev.5.0 <3.0.0"

dependencies:
  collection: ^1.14.12
  path: ^1.6.4
  crypto: ^2.1.3
  quiver: ^2.0.5
  characters: ^0.3.1

dev_dependencies:
  test: ^1.9.2
  pedantic: ^1.8.0