name: Dart CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["2.7", "2.8", "2.9", "2.10", "dev"]

    container:
      image:  google/dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test

  test-windows:
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
      - name: Install dart
        run: |
          choco install dart-sdk
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: C:\tools\dart-sdk\bin\pub.bat get
      - name: Run tests
        run: C:\tools\dart-sdk\bin\pub.bat run test

  test-macos:
    timeout-minutes: 5
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tap Google's Dart formula repository
        run: brew tap dart-lang/dart
      - name: Install the Dart formula
        run: brew install dart
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test

  format:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    container:
      image:  google/dart:dev

    steps:
      - uses: actions/checkout@v1
      - name: Dartfmt
        run: dartfmt --set-exit-if-changed -w --fix .
